name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: mkdir out
      run: docker build --tag onlyoffice-document-editors-builder .
      run: docker run -v $PWD/out:/build_tools/out onlyoffice-document-editors-builder
